export const mockDeals = [
  {
    id: "1",
    title: "Delicious Pizza Combo",
    description: "Large pizza with 2 toppings + garlic bread + cold drink",
    originalPrice: 899,
    discountedPrice: 599,
    discount: 33,
    category: "Food",
    merchant: "Pizza Palace",
    location: "Connaught Place",
    distance: "0.8 km",
    rating: 4.5,
    expiresAt: "Today",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "2",
    title: "Trendy Summer Collection",
    description: "Buy 2 Get 1 Free on all summer wear including t-shirts, shorts",
    originalPrice: 2999,
    discountedPrice: 1999,
    discount: 33,
    category: "Fashion",
    merchant: "Fashion Hub",
    location: "Karol Bagh",
    distance: "1.2 km",
    rating: 4.2,
    expiresAt: "2 days",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "3",
    title: "Wireless Bluetooth Headphones",
    description: "Premium quality wireless headphones with noise cancellation",
    originalPrice: 4999,
    discountedPrice: 2999,
    discount: 40,
    category: "Electronics",
    merchant: "Tech Store",
    location: "Nehru Place",
    distance: "2.1 km",
    rating: 4.7,
    expiresAt: "5 days",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "4",
    title: "Healthy Meal Combo",
    description: "Grilled chicken salad + fresh juice + soup of the day",
    originalPrice: 450,
    discountedPrice: 299,
    discount: 34,
    category: "Food",
    merchant: "Healthy Bites",
    location: "Lajpat Nagar",
    distance: "1.5 km",
    rating: 4.3,
    expiresAt: "Today",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "5",
    title: "Designer Handbag Collection",
    description: "Exclusive designer handbags with premium leather finish",
    originalPrice: 3500,
    discountedPrice: 2100,
    discount: 40,
    category: "Fashion",
    merchant: "Style Studio",
    location: "Khan Market",
    distance: "0.9 km",
    rating: 4.6,
    expiresAt: "3 days",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "6",
    title: "Smartphone Accessories Bundle",
    description: "Phone case + screen protector + wireless charger combo",
    originalPrice: 1999,
    discountedPrice: 1199,
    discount: 40,
    category: "Electronics",
    merchant: "Mobile World",
    location: "Gaffar Market",
    distance: "1.8 km",
    rating: 4.1,
    expiresAt: "1 week",
    image: "/placeholder.svg?height=200&width=300",
  },
]

export const categories = [
  { id: "all", name: "All Categories", icon: "🏪" },
  { id: "food", name: "Food & Dining", icon: "🍕" },
  { id: "fashion", name: "Fashion & Style", icon: "👕" },
  { id: "electronics", name: "Electronics", icon: "📱" },
  { id: "health", name: "Health & Beauty", icon: "💄" },
  { id: "home", name: "Home & Garden", icon: "🏠" },
  { id: "sports", name: "Sports & Fitness", icon: "⚽" },
]
